// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbIOfICSYsZ8XQ6vR3qbpYSvchRAqsBGQ',
    appId: '1:879170194555:web:86bc6ae74d4e400eea66de',
    messagingSenderId: '879170194555',
    projectId: 'electricity-management-2026',
    authDomain: 'electricity-management-2026.firebaseapp.com',
    storageBucket: 'electricity-management-2026.firebasestorage.app',
    measurementId: 'G-6MRQV5K9T4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKLBxaSGTg6mkNda4yzm6Mep1yl4zxbZA',
    appId: '1:879170194555:android:d6a1c998b32b91d0ea66de',
    messagingSenderId: '879170194555',
    projectId: 'electricity-management-2026',
    storageBucket: 'electricity-management-2026.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJYoGMT3t6yM0vKcvRKpYN-6GyJKuOUxI',
    appId: '1:879170194555:ios:8e24f67a87d8b5a9ea66de',
    messagingSenderId: '879170194555',
    projectId: 'electricity-management-2026',
    storageBucket: 'electricity-management-2026.firebasestorage.app',
    iosBundleId: 'com.example.electricityManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJYoGMT3t6yM0vKcvRKpYN-6GyJKuOUxI',
    appId: '1:879170194555:ios:8e24f67a87d8b5a9ea66de',
    messagingSenderId: '879170194555',
    projectId: 'electricity-management-2026',
    storageBucket: 'electricity-management-2026.firebasestorage.app',
    iosBundleId: 'com.example.electricityManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbIOfICSYsZ8XQ6vR3qbpYSvchRAqsBGQ',
    appId: '1:879170194555:web:c09d84cb7d05a006ea66de',
    messagingSenderId: '879170194555',
    projectId: 'electricity-management-2026',
    authDomain: 'electricity-management-2026.firebaseapp.com',
    storageBucket: 'electricity-management-2026.firebasestorage.app',
    measurementId: 'G-TDWPJ3V544',
  );
}
